CREATE TABLE personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(8) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nac DATE,
    genero VARCHAR(1),
    telefono VARCHAR(20),
    direccion VARCHAR(200),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE docentes (
    id BIGINT PRIMARY KEY REFERENCES personas(id),
    codigo_empleado VARCHAR(20) NOT NULL UNIQUE,
    especialidad VARCHAR(100) NOT NULL,
    tipo_contrato VARCHAR(30),
    carga_horaria_max INTEGER
);

CREATE TABLE estados_alumno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    es_terminal BOOLEAN DEFAULT FALSE,
    es_transitorio BOOLEAN DEFAULT FALSE,
    permiso_acceso BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE alumnos (
    id BIGINT PRIMARY KEY REFERENCES personas(id),
    codigo_estudiante VARCHAR(20) NOT NULL UNIQUE,
    estado_actual_id BIGINT REFERENCES estados_alumno(id),
    sub_estado VARCHAR(30),
    fecha_ingreso DATE,
    fecha_ultimo_estado TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE padres (
    id BIGINT PRIMARY KEY REFERENCES personas(id),
    parentesco VARCHAR(20),
    es_titular BOOLEAN DEFAULT FALSE
);

CREATE TABLE alumnos_padres (
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    padre_id BIGINT NOT NULL REFERENCES padres(id),
    PRIMARY KEY (alumno_id, padre_id)
);

CREATE TABLE transiciones_estado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_origen_id BIGINT NOT NULL REFERENCES estados_alumno(id),
    estado_destino_id BIGINT NOT NULL REFERENCES estados_alumno(id),
    codigo_gatillante VARCHAR(30) NOT NULL,
    es_automatica BOOLEAN DEFAULT FALSE,
    requiere_admin BOOLEAN DEFAULT TRUE,
    requiere_consejo BOOLEAN DEFAULT FALSE,
    notifica_padre BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (estado_origen_id, estado_destino_id, codigo_gatillante)
);

CREATE TABLE historial_estados_alumno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    estado_anterior_id BIGINT REFERENCES estados_alumno(id),
    estado_nuevo_id BIGINT NOT NULL REFERENCES estados_alumno(id),
    motivo VARCHAR(1000) NOT NULL,
    documento_url VARCHAR(500),
    fecha_cambio TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE grados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    orden INTEGER NOT NULL,
    capacidad_max INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE secciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    capacidad INTEGER NOT NULL,
    grado_id BIGINT NOT NULL REFERENCES grados(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE aulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    capacidad INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE materias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    horas_semanales_req INTEGER,
    tipo VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE periodos_academicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id BIGINT NOT NULL REFERENCES periodos_academicos(id),
    grado_id BIGINT NOT NULL REFERENCES grados(id),
    seccion_id BIGINT NOT NULL REFERENCES secciones(id),
    materia_id BIGINT NOT NULL REFERENCES materias(id),
    docente_id BIGINT REFERENCES docentes(id),
    aula_id BIGINT REFERENCES aulas(id),
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (periodo_id, grado_id, seccion_id, materia_id)
);

CREATE TABLE horario_bloques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    aula_id BIGINT REFERENCES aulas(id),
    dia_semana INTEGER NOT NULL,
    hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL,
    hora_fin TIME(0) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (curso_id, dia_semana, hora_inicio)
);

CREATE TABLE sesiones_clase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    horario_bloque_id BIGINT REFERENCES horario_bloques(id),
    fecha DATE NOT NULL,
    hora_inicio TIME(0) WITHOUT TIME ZONE,
    hora_fin TIME(0) WITHOUT TIME ZONE,
    tema VARCHAR(300),
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE bimestres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id BIGINT NOT NULL REFERENCES periodos_academicos(id),
    numero INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (periodo_id, numero)
);

CREATE TABLE tipos_evaluacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    peso_porcentaje DOUBLE PRECISION NOT NULL,
    orden INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE evaluaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    bimestre_id BIGINT NOT NULL REFERENCES bimestres(id),
    tipo_evaluacion_id BIGINT NOT NULL REFERENCES tipos_evaluacion(id),
    nombre VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    ponderacion_override DOUBLE PRECISION,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (curso_id, bimestre_id, tipo_evaluacion_id, nombre)
);

CREATE TABLE notas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id BIGINT NOT NULL REFERENCES evaluaciones(id),
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    valor DECIMAL(4,2) NOT NULL,
    observacion VARCHAR(500),
    registrado_por VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (evaluacion_id, alumno_id)
);

CREATE TABLE asistencias_alumno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id BIGINT NOT NULL REFERENCES sesiones_clase(id),
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    tipo_asistencia VARCHAR(20) NOT NULL,
    minutos_tardanza INTEGER,
    observacion VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL,
    UNIQUE (sesion_id, alumno_id)
);

CREATE TABLE alertas_faltas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    cantidad_consecutivas INTEGER NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    fechas JSONB,
    resuelta_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE conceptos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    monto_base DECIMAL(10,2) NOT NULL,
    periodicidad VARCHAR(30),
    grado_id BIGINT REFERENCES grados(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE cronograma_pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto_pago_id BIGINT NOT NULL REFERENCES conceptos_pago(id),
    periodo_id BIGINT NOT NULL REFERENCES periodos_academicos(id),
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    fecha_vencimiento DATE NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cronograma_pago_id BIGINT NOT NULL REFERENCES cronograma_pagos(id),
    alumno_id BIGINT NOT NULL REFERENCES alumnos(id),
    monto DECIMAL(10,2) NOT NULL,
    metodo VARCHAR(30),
    referencia VARCHAR(100),
    fecha_pago DATE NOT NULL,
    usuario_id BIGINT,
    stripe_payment_intent_id VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(100) NOT NULL,
    modulo VARCHAR(30),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE roles_permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id BIGINT NOT NULL REFERENCES roles(id),
    permiso_id BIGINT NOT NULL REFERENCES permisos(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMP(6) WITH TIME ZONE,
    persona_id BIGINT UNIQUE REFERENCES personas(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE roles_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    rol_id BIGINT NOT NULL REFERENCES roles(id),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    titulo VARCHAR(200) NOT NULL,
    cuerpo VARCHAR(2000) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    leida BOOLEAN DEFAULT FALSE,
    entidad_tipo VARCHAR(50),
    entidad_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);

CREATE TABLE documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad_tipo VARCHAR(50) NOT NULL,
    entidad_id BIGINT NOT NULL,
    tipo_doc VARCHAR(30) NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100),
    generado_por VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    version INTEGER NOT NULL
);
